version: '3'

services:

  manager-db:
    image: postgres:15                # busca directamente la imagen de postgres (primero local sino en docker hub)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    container_name: "manager-local"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
      AUTH_CLIENT_ID_M2M: ${AUTH_CLIENT_ID_M2M}
      AUTH_CLIENT_SECRET_M2M: ${AUTH_CLIENT_SECRET_M2M}
      AUTH_ISSUER_URI: ${AUTH_ISSUER_URI}
      AUTH0_AUDIENCE_M2M: ${AUTH0_AUDIENCE_M2M}
    depends_on:
      - manager-db

volumes:
  postgres-data:
