version: '3'

services:

  db:
    image: postgres:15                # busca directamente la imagen de postgres (primero local sino en docker hub)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env



volumes:
  postgres-data:
