version: '3'

services:

  manager-db:
    image: postgres:15                # busca directamente la imagen de postgres (primero local sino en docker hub)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    container_name: "manager-local"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_STREAM_REQUEST_LINT_KEY: ${REDIS_REQUEST_KEY}
      REDIS_STREAM_RESULT_LINT_KEY: ${REDIS_RESULT_KEY}
      REDIS_STREAM_GROUP_LINT: ${REDIS_GROUP_KEY}
    depends_on:
      - manager-db
      - redis


  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
